import { ReactNode } from "react";

import type { Metadata } from "next";
import "@/app/globals.css";
import { AuthProvider } from "@/components/AuthProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
import {
	Sheet,
	SheetContent,
	SheetDescription,
	SheetTitle,
	SheetTrigger,
} from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { MenuIcon } from "lucide-react";
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import {
	LoginLink,
	LogoutLink,
	RegisterLink,
} from "@kinde-oss/kinde-auth-nextjs/components";
import Image from "next/image";
import Link from "next/link";
import StoreNavigation from "@/components/Store/StoreNavigation";
import ShoppingCart from "@/components/Store/ShoppingCart";

export default async function StoreLayout({
	children,
}: {
	children: ReactNode;
}) {
	const { getUser } = getKindeServerSession();
	const user = await getUser();

	return (
		<AuthProvider>
			<html lang="en">
				<body className="">
					<div className="flex w-full flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
						<header className="sticky top-0 flex h-16 items-center justify-between gap-4 border-b bg-white z-50">
							<nav className="hidden font-medium md:flex md:flex-row  md:items-center  md:gap-5 md:text-sm lg:gap-6">
								<Link href="/">
									<div className="flex mr-6 -mt-3 items-center ">
										<span className="font-extrabold  text-4xl">+</span>
										<p className="text-4xl font-bold bg-gradient-to-r tracking-tight from-blue-800 to-blue-200 text-transparent bg-clip-text  ">
											Store
										</p>
									</div>
								</Link>
								<StoreNavigation />
							</nav>

							<Sheet>
								<SheetTrigger asChild>
									<Button
										className="shrink-0 md:hidden"
										variant="outline"
										size="icon"
									>
										<MenuIcon className="h-5 w-5" />
									</Button>
								</SheetTrigger>
								<SheetTitle></SheetTitle>
								<SheetDescription></SheetDescription>
								<SheetContent side="left">
									<nav className="flex flex-col gap-6 text-lg font-medium mt-5">
										<StoreNavigation />
									</nav>
								</SheetContent>
							</Sheet>
							<div className="flex flex-row justify-between gap-3">
								<ShoppingCart></ShoppingCart>
								{user ? (
									<div className=" flex justify-between items-center gap-4">
										{user?.email == process.env.ADMIN_EMAIL && (
											<Button>
												<Link href="/dashboard">Go to Dashboard</Link>
											</Button>
										)}
										<DropdownMenu>
											<DropdownMenuTrigger asChild>
												<button>
													<Image
														src={
															user?.picture ??
															"https://avatar.vercel.sh/rauchg.svg?text=User"
														}
														alt="profile"
														width={33}
														height={33}
														className="rounded-full"
													></Image>
												</button>
											</DropdownMenuTrigger>
											<DropdownMenuContent align="end">
												<DropdownMenuLabel>{user.email}</DropdownMenuLabel>
												<DropdownMenuSeparator />
												<DropdownMenuItem asChild>
													<LogoutLink>Logout</LogoutLink>
												</DropdownMenuItem>
											</DropdownMenuContent>
										</DropdownMenu>
									</div>
								) : (
									<div className="flex justify-between gap-3">
										<Button asChild className="">
											<LoginLink>Log In</LoginLink>
										</Button>
										<Button asChild className="">
											<RegisterLink> Create Account</RegisterLink>
										</Button>
									</div>
								)}
							</div>
						</header>
						<main className="my-5">{children}</main>
					</div>
					<footer className="m-10 px-4 text-center text-gray-500">
						<small className="mb-2 block text-xs">
							&copy; 2025 Mhd Hassan. All rights reserved.
						</small>
						<p className="text-xs">
							<span className="font-semibold">About this website:</span> built
							with React & Next.js (App Router & Server Actions), TypeScript,
							Tailwind CSS, Chadcn, Redis & Upstash, Prisma, uploadthing, Vercel
							hosting.
						</p>
					</footer>
				</body>
			</html>
		</AuthProvider>
	);
}
